name: Local Dev
values:
  - key: baseURL
    value: 'http://localhost:3001'
  - key: accessToken
    value: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0N2I1OTE4ZS1hNjVlLTQ0ZWQtYTk1My02ZjJhMjUyMDkwMGUiLCJlbWFpbCI6ImxvZ2ludGVzdEBleGFtcGxlLmNvbSIsImlhdCI6MTc4NTYwNTA3NiwiZXhwIjoxNzg1NjA1OTc2fQ.sRCAEiz-W9NGplUWaKq5VFKttU9IMsTYxs459rh2nII'
  - key: refreshToken
    value: ''
