name: Local Dev
values:
  - key: baseURL
    value: 'http://localhost:3001'
  - key: accessToken
    value: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1YWY4N2QyYy1kNmY1LTQxNTktOWUwNS1iNzJiMWFlMzM1YTEiLCJlbWFpbCI6ImxvZ2ludGVzdEBleGFtcGxlLmNvbSIsImlhdCI6MTc4NTY1NjkzNiwiZXhwIjoxNzg1NjU3ODM2fQ.ELvopNZ8FHZKof5NRX4PWo12PmYl3pk4Z6eJmQ3jCfk'
  - key: refreshToken
    value: ''
